enable:
    - admin
    - alert
    - find
    - list
    - message
    - send
    - sendall
    - slap
format:
    admin: '&c[{{ SERVER }}, {{ SENDER }}] &7{{ MESSAGE }}'
    alert: '&8[&a+&8] &7{{ ALERT }}'
    find: '&e{{ PLAYER }} &ais playing on &e{{ SERVER }}'
    message: '&a({{ SERVER }}) &7[{{ SENDER }} {{ RAQUO }} {{ RECIPIENT }}] &f{{ MESSAGE }}'
    send: '&aSending &e{{ PLAYER }} &ato server &e{{ SERVER }}'
settings:
    glist:
        header: '&aServers:'
        body: '&a- {{ SERVER }} {{ DENSITY }}'
errors:
    invalid: '&cInvalid arguments provided.'
    offline: '&cSorry, that player is offline.'
    slap: '&cYou are unworthy of slapping people.'
