enable:
  - alert
  - announcement
  - autoredirect
  - commandspy
  - fastrelog
  - hide
  - joinannounce
  - lookup
  - mute
  - send
  - sendall
  - spy
  - staffchat
  - chat
  - find
  - ignore
  - join
  - list
  - message
  - slap
  - aliases
  #- betaupdates
  #- clean
  - fulllog
  - log
  - rules
  - rules-chat
  - spam
  - spam-chat
  - spam-command
  - updater
commands:
  alert:
    - 'alert'
    - 'broadcast'
  commandspy:
    - 'commandspy'
    - 'cspy'
  hide:
    - 'hide'
  lookup:
    - 'lookup'
  mute:
    - 'bmute'
  send:
    - 'send'
  sendall:
    - 'sendall'
  spy:
    - 'spy'
    - 'socialspy'
  staffchat:
    - 'staffchat'
    - 'admin'
    - 'a'
    - 'sc'
  chat:
    - 'g'
    - 'global'
  find:
    - 'find'
    - 'whereis'
  ignore:
    - 'bignore'
  join:
    - 'join'
  list:
    - 'glist'
    - 'servers'
    - 'serverlist'
  message:
    - 'message'
    - 'msg'
    - 'm'
    - 'pm'
    - 't'
    - 'tell'
    - 'w'
    - 'whisper'
  reply:
    - 'reply'
    - 'r'
  slap:
    - 'slap'
    - 'uslap'
    - 'smack'
  reload:
    - 'gssreload'
aliases:
  - alias: 'greet'
    commands:
      - 'TELL {0}: {{ PLAYER }} was at {{ SERVER }} but is coming to join you!'
      - 'join {0}'
  - alias: 'disappear'
    commands:
      - 'spy'
      - 'cspy'
      - 'hide'
  - alias: 'vote'
    commands:
      - 'CONSOLE: staffchat {{ PLAYER }} wants to vote!'
      - 'TELL: Vote for the server at yourvote.site!'
configversion: 2.4.6
