enable:
  - staffchat
  - alert
  - find
  - hide
  - join
  - list
  - log
  - message
  # - multilog
  - rules
  - rules-chat
  - send
  - sendall
  - spam
  - spam-chat
  - slap
  - spy
  - commandspy
  - joinannounce
  - announcement
  - updater
  - aliases
  - chat
  - lookup
  - ignore
  - mute
  # - clean
  # - betaupdates
commands:
  staffchat:
    - 'staffchat'
    - 'admin'
    - 'a'
    - 'sc'
  chat:
    - 'g'
    - 'global'
  alert:
    - 'alert'
    - 'broadcast'
  find:
    - 'find'
    - 'whereis'
  hide:
    - 'hide'
  join:
    - 'join'
  list:
    - 'glist'
    - 'servers'
    - 'serverlist'
  message:
    - 'message'
    - 'msg'
    - 'm'
    - 'pm'
    - 't'
    - 'tell'
    - 'w'
    - 'whisper'
  reply:
    - 'reply'
    - 'r'
  send:
    - 'send'
  sendall:
    - 'sendall'
  slap:
    - 'slap'
    - 'uslap'
    - 'smack'
  spy:
    - 'spy'
    - 'socialspy'
  commandspy:
    - 'commandspy'
    - 'cspy'
  reload:
    - 'gssreload'
  lookup:
    - 'lookup'
  ignore:
    - 'bignore'
  mute:
    - 'bmute'
aliases:
  - alias: 'greet'
    commands:
      - 'msg {0} Hey! How are you doing today? I was at {{ SERVER }} but I''m coming to join you!'
      - 'join {0}'
  - alias: 'disappear'
    commands:
      - 'spy'
      - 'cspy'
      - 'hide'

#DO NOT CHANGE!
configversion: '2.4.4'
