enable:
  - staffchat
  - alert
  - find
  - hide
  - join
  - list
  - log
  - message
  # - multilog
  - rules
  - rules-chat
  - send
  - sendall
  - spam
  - spam-chat
  - slap
  - spy
  - commandspy
  - joinannounce
  - announcement
  - updater
  - aliases
  - chat
  - lookup
  - ignore
  - mute
  # - clean
  # - betaupdates
commands:
  staffchat:
    - 'staffchat'
    - 'admin'
    - 'a'
    - 'sc'
  chat:
    - 'g'
    - 'global'
  alert:
    - 'alert'
    - 'broadcast'
  find:
    - 'find'
    - 'whereis'
  hide:
    - 'hide'
  join:
    - 'join'
  list:
    - 'glist'
    - 'servers'
    - 'serverlist'
  message:
    - 'message'
    - 'msg'
    - 'm'
    - 'pm'
    - 't'
    - 'tell'
    - 'w'
    - 'whisper'
  reply:
    - 'reply'
    - 'r'
  send:
    - 'send'
  sendall:
    - 'sendall'
  slap:
    - 'slap'
    - 'uslap'
    - 'smack'
  spy:
    - 'spy'
    - 'socialspy'
  commandspy:
    - 'commandspy'
    - 'cspy'
  reload:
    - 'gssreload'
  lookup:
    - 'lookup'
  ignore:
    - 'bignore'
  mute:
    - 'bmute'
aliases:
  - alias: 'greet'
    commands:
      - 'msg {0} Hey! How are you doing today?'
      - 'join {0}'
  - alias: 'disappear'
    commands:
      - 'spy'
      - 'cspy'
      - 'hide'
format:
  alert: '&8[&b!&8] &7{{ MESSAGE }}'
  join: '&8[&a+&8] &7{{ PLAYER }}'
  quit: '&8[&c-&8] &7{{ PLAYER }}'
  find: '&e{{ PLAYER }} &ais playing on &e{{ SERVER }}'
  message: '&a({{ SERVER }}) &7[{{ SENDER }} » {{ RECIPIENT }}] &f{{ MESSAGE }}'
  send: '&aSending &e{{ PLAYER }} &ato server &e{{ SERVER }}'
warnings:
  similarity: '&cPlease do not spam other players!'
  swearing: '&cPlease do not swear at other players!'
  advertising: '&cPlease do not advertise other servers!'
rules:
  - pattern: '\bfuck\b'
    handle: CURSING
  - pattern: '^.+((\.|dot).+)*(\.|dot)\s*[a-zA-Z]{2,5}'
    handle: ADVERTISEMENT
  - pattern: '(\d{1,4}\.){3}\d{1,4}'
    handle: ADVERTISEMENT
  - pattern: 'asshole'
    handle: REPLACE
    replacement: '******'
  - pattern: 'I hate (this|your) server'
    handle: REPLACE
    replacement: 'I love this server'
  - pattern: 'I hate (this|your) server'
    handle: COMMAND
    command: 'send {{ SENDER }} lobby'
rulenotify:
  advertisement: '&7{{ PLAYER }} just advertised!'
  cursing: '&7{{ PLAYER }} just sweared!'
  replace: '&7{{ PLAYER }} sweared but was replaced!'
  command: '&7{{ PLAYER }} sweared, triggering a command!'
staffchat:
  message: '&c{{ SERVER }} - {{ SENDER }} » &7{{ MESSAGE }}'
  enabled: '&aYou are now chatting in staff chat!'
  disabled: '&cYou are no longer chatting in staff chat!'
chat:
  message: '&e{{ SERVER }} - {{ SENDER }} » &7{{ MESSAGE }}'
  enabled: '&aYou are now chatting in global chat!'
  disabled: '&cYou are no longer chatting in global chat!'
list:
  header: '&aServers:'
  body: '&a- {{ SERVER }} {{ DENSITY }}'
lookup:
  header: '&6Found {{ SIZE }} player(s):'
  body: '&f - {{ PLAYER }}'
multilog:
  limit: 3
  kicked: '&cMaximum number of connections reached!'
spy:
  message: '&7[{{ SENDER }} » {{ RECIPIENT }}] &7{{ MESSAGE }}'
  enabled: '&aSpy has been enabled'
  disabled: '&cSpy has been disabled'
commandspy:
  command: '&7[{{ SENDER }}] &b{{ COMMAND }}'
  enabled: '&aCommand Spy has been enabled'
  disabled: '&cCommand Spy has been disabled'
hide:
  enabled: '&aYou are now hidden from all players!'
  disabled: '&cYou are now visible to all players!'
ignore:
  enabled: '&6Now ignoring {{ PLAYER }}.'
  disabled: '&6No longer ignoring {{ PLAYER }}.'
slap:
  slapper: '&aYou just slapped &e{{ SLAPPED }}&a. I bet that felt good, didn't it?'
  slapped: '&cYou were just slapped by &e{{ SLAPPER }}&c! Ouch! (/slap him back!)'
mute:
  enabled: '&cYou are now muted!'
  disabled: '&aYou are no longer muted!'
  error: '&cHey, you can't chat while muted!'
errors:
  invalid: '&cInvalid arguments provided. Usage: {{ HELP }}'
  offline: '&cSorry, that player is offline.'
  slap: '&cYou are unworthy of slapping people.'
  messages: '&cNobody has messaged you recently.'
  ignoreself: '&cYou can't ignore yourself!'
  ignoring: '&cYou can't send a message to someone you're ignoring!'
  sendfail: '&cUnable to send {{ PLAYER }} to {{ SERVER }}.'
announcements:
# Time measured in seconds
  - delay: 30
    interval: 60
    message: 'Vote for our server for great rewards!'
  - delay: 0
    interval: 60
    message: 'Donate to support our server!/n&f&ndonate.myserver.com'
